// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hiB4DjyRHqRnuTjs3hSpg3
// Component: lw5RrOvvSze475
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: pJUg0QXd-cEaek/component
import Button from "../../Button"; // plasmic-import: bPebpRL-4Thq2C/component
import ProductCard from "../../ProductCard"; // plasmic-import: wmPxe-0hn60BPc/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: 7bj-pEPEi9Jpua/component
import Value from "../../Value"; // plasmic-import: tq51gU2wX-A9Kh/component
import Footer from "../../Footer"; // plasmic-import: 2too7_o7qNE7ni/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 2IbRVinUUFLL1i/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: hiB4DjyRHqRnuTjs3hSpg3/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: lw5RrOvvSze475/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: kcV-U-yG9ZD00R/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: gkD4FG0PFBHYu5/icon
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: QbhQgfdhfeuwt6/icon
import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: 8SLVpF7NhxFk7x/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: FfUfBsosBNg-UW/icon
import Icon23Icon from "./icons/PlasmicIcon__Icon23"; // plasmic-import: l3Xyb4BcW0iKGE/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: SUaP3sp9YamHTc/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: ZJhdRk4KTuexf0/icon
import Icon18Icon from "./icons/PlasmicIcon__Icon18"; // plasmic-import: sM52KpuTzteaz7/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: tMMKBNMRH-DVtk/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: NGPtqng7lHomXQ/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: fMDvST1P2RKtcR/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: Dz6r5j1n8egGxq/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  children?: React.ReactNode;
  children2?: React.ReactNode;
  children22?: React.ReactNode;
  children222?: React.ReactNode;
  children2222?: React.ReactNode;
  children22222?: React.ReactNode;
  container42?: React.ReactNode;
  children4?: React.ReactNode;
  children24?: React.ReactNode;
  children224?: React.ReactNode;
  children2224?: React.ReactNode;
  children22224?: React.ReactNode;
  children222223?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>(
  "children",
  "children2",
  "children22",
  "children222",
  "children2222",
  "children22222",
  "container42",
  "children4",
  "children24",
  "children224",
  "children2224",
  "children22224",
  "children222223"
);

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  container3?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  container4?: p.Flex<"div">;
  container?: p.Flex<"div">;
  container43?: p.Flex<"div">;
  emojiValueProps?: p.Flex<typeof EmojiValueProps>;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  container6?: p.Flex<"div">;
  container434?: p.Flex<"div">;
  container433?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
  textbox?: p.Flex<"input">;
};

export interface DefaultHomepageProps {
  dataFetches: PlasmicHomepage__Fetches;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"ShoeShop"}</title>
        <meta key="og:title" property="og:title" content={"ShoeShop"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a."
          }
        />
      </Head>

      <style global jsx>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section__kCuRn)}>
            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__vtOa)}
              role={"img"}
              src={
                "https://images.unsplash.com/photo-1522158073024-fb5d4b4ccfdf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2048&q=80" as const
              }
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container3)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__q5Pk1)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__wmj3Y)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      defaultcss.h1,
                      defaultcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection "}
                  </h1>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__yzBfL
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </p.Stack>

                <Button
                  children2={
                    <Icon5Icon
                      className={classNames(defaultcss.all, sty.svg__ekzsE)}
                      role={"img"}
                    />
                  }
                  className={classNames("__wab_instance", sty.button__vQdii)}
                  colors={"black" as const}
                  icons={"end" as const}
                  link2={"/category" as const}
                  rounded={"rounded" as const}
                  size={"large" as const}
                  slot={"Shop"}
                />
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__mr7M)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(defaultcss.all, sty.container4)}
            >
              <div className={classNames(defaultcss.all, sty.box___1HCzD)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__dd70N
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  children2={
                    <Icon5Icon
                      className={classNames(defaultcss.all, sty.svg__x7Oe3)}
                      role={"img"}
                    />
                  }
                  className={classNames("__wab_instance", sty.button__nYDmT)}
                  icons={"end" as const}
                  link={"link" as const}
                  link2={"/category" as const}
                  slot={"See more"}
                />
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__qzq6S)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__kldSv)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg" as const
                      }
                    />
                  ),

                  value: args.children
                })}
                link={"/item" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___2SoYd
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___0FqRa
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__hYmXy)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__xcTfd)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/79d40e0b-da9d-4049-a4be-6a8fe7d9489e/air-zoom-pegasus-38-womens-running-shoe-2bvJvW.png" as const
                      }
                    />
                  ),

                  value: args.children2
                })}
                link={"/item" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__jLyDd
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__sTt8G
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__o8Eci)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__a8DHk)}
                      role={"img"}
                      src={
                        "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/3108369a42714ba6a9c2aa99017b457a_9366/Club_C_85_Vintage_Men's_Shoes_White_V67899_01_standard.jpg" as const
                      }
                    />
                  ),

                  value: args.children22
                })}
                link={"/item" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__kXjcL
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__n6CCd
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__ytRx)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__eAkBu)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b13d4f77-9404-492f-b2c8-5f06419f2cb6/air-max-genome-mens-shoe-hgsQFb.png" as const
                      }
                    />
                  ),

                  value: args.children222
                })}
                link={"/item" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__yrTms
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__uhtu
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__llzmp)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__w1S6O)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/cdfdf1409e054322b9e0ac6d011da5e2_9366/Ultraboost_DNA_1.0_Shoes_Green_H05264_01_standard.jpg" as const
                      }
                    />
                  ),

                  value: args.children2222
                })}
                link={"/item" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__lMddL
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__i9Vjj
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__luYCl)}
                image={p.renderPlasmicSlot({
                  defaultContents: (
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__wpTPx)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f6cbde42-eed6-42bd-b5d9-1b5bef129618/zion-1-big-kids-shoe-BsvRq7.png" as const
                      }
                    />
                  ),

                  value: args.children22222
                })}
                link={"/item" as const}
              />
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__p12Wg)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container43"}
              data-plasmic-override={overrides.container43}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container43)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__pXLfQ)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__dG0Dn)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__kxprS
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nya6O
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__dC9Mx)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___9Ba9
                    )}
                  >
                    <span>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span style={{ fontStyle: "italic" }}>{"for"}</span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </span>
                  </div>

                  <Button
                    children2={
                      <Icon5Icon
                        className={classNames(defaultcss.all, sty.svg__oqWyB)}
                        role={"img"}
                      />
                    }
                    colors={"black" as const}
                    icons={"end" as const}
                    link2={"/category" as const}
                    rounded={"rounded" as const}
                    size={"large" as const}
                    slot={"Shop sale"}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          />

          <section className={classNames(defaultcss.all, sty.section__oyPwO)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div className={classNames(defaultcss.all, sty.box__fux6)}>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__um1Zq
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      children2={
                        <Icon5Icon
                          className={classNames(defaultcss.all, sty.svg__oJ419)}
                          role={"img"}
                        />
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button__eCjEc
                      )}
                      icons={"end" as const}
                      link={"link" as const}
                      link2={"/category" as const}
                      slot={"See more"}
                    />
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__wx6HP)}
              >
                <ProductCard
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__k4Fp)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg" as const
                        }
                      />
                    ),

                    value: args.children4
                  })}
                  link={"http://google.com" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___66E9Q
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__e6V7V
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__vGhBe
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__sDz6H)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/79d40e0b-da9d-4049-a4be-6a8fe7d9489e/air-zoom-pegasus-38-womens-running-shoe-2bvJvW.png" as const
                        }
                      />
                    ),

                    value: args.children24
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__duUn5
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__xfkTg
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__p7HK
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__s3Jar)}
                        role={"img"}
                        src={
                          "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/3108369a42714ba6a9c2aa99017b457a_9366/Club_C_85_Vintage_Men's_Shoes_White_V67899_01_standard.jpg" as const
                        }
                      />
                    ),

                    value: args.children224
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__cjjyD
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__sMuda
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wZ2Jq
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__obS8M)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b13d4f77-9404-492f-b2c8-5f06419f2cb6/air-max-genome-mens-shoe-hgsQFb.png" as const
                        }
                      />
                    ),

                    value: args.children2224
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__eCmGg
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__e21X
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lo9Pk
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__rndzw)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/cdfdf1409e054322b9e0ac6d011da5e2_9366/Ultraboost_DNA_1.0_Shoes_Green_H05264_01_standard.jpg" as const
                        }
                      />
                    ),

                    value: args.children22224
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___0I1Ob
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__bKxq
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__w3Bw3
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__vuodj)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f6cbde42-eed6-42bd-b5d9-1b5bef129618/zion-1-big-kids-shoe-BsvRq7.png" as const
                        }
                      />
                    ),

                    value: args.children222223
                  })}
                  link={"http://google.com" as const}
                />
              </p.Stack>
            </div>
          </section>

          <section className={classNames(defaultcss.all, sty.section___4Yl81)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__aHIl)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__amSIa
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__yiGl)}
                  icons={"none" as const}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__cxtD
                      )}
                    >
                      {"All"}
                    </div>
                  }
                  states={"active" as const}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__eD1N)}
                  icons={"none" as const}
                  slot={"New"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__rhRmT)}
                  icons={"none" as const}
                  slot={"Womens"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__ravnr)}
                  icons={"none" as const}
                  slot={"Mens"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__xgreZ)}
                  icons={"none" as const}
                  slot={"Kids"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button___37Z2D)}
                  icons={"none" as const}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__phEwe
                      )}
                    >
                      {"On sale"}
                    </div>
                  }
                />
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__mzmtp)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__g3Xul
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__kUlPb)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/0a659aab-5bb4-471e-adb3-beaf9be6e737/air-zoom-pegasus-38-limited-edition-womens-running-shoe-vmTQVG.png" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__w729H
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__jGHpe
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__buoLo
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___5Qgbu)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/32735c84c423487da282ac790116ced8_9366/NMD_R1_Shoes_Blue_G55574_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__pSyHl
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__oxTXk
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ocOp0
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__osHfj)}
                      role={"img"}
                      src={
                        "https://assets.reebok.com/images/w_320,f_auto,q_auto:sensitive,fl_lossy/dc6b2176848c4116b789acde0138ff10_9366/Question_Low_Men's_Basketball_Shoes_White_GV7629_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__x7QYb
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ubxG4
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qtnzK
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__fiuSi)}
                      role={"img"}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/369155/04/sv03/fnd/PNA/fmt/png/Cali-Women's-Sneakers" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nt8AE
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__j7Zq
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ppJjw
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__kwp2G)}
                      role={"img"}
                      src={
                        "https://images.asics.com/is/image/asics/1011B026_600_SR_RT_GLB?$zoom$" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___3LyMh
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___8STrC
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__iPfMg
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__lIjEp)}
                      role={"img"}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwfa98a04a/images/a_107/170823C_A_107X1.jpg?sw=964" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__fyqCx
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__sv8YX
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__b9Tqt
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__ky0Rh)}
                      role={"img"}
                      src={
                        "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/c636bdcc-1f55-4cf5-9113-021b47c2fa86/air-zoom-pegasus-38-womens-running-shoe-wide-5JxKzR.png" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__lwjhU
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ll8GN
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zmWzh
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__v43LS)}
                      role={"img"}
                      src={
                        "https://images.asics.com/is/image/asics/1011A780_100_SR_RT_GLB?$zoom$" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__vHxg
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___1LfVc
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qhSuk
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__i1C3)}
                      role={"img"}
                      src={
                        "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw388d0c95/images/a_107/670880C_A_107X1.jpg?sw=964" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nHp8A
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__tbpWz
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___8S3Vp
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__rGjz0)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto:sensitive,fl_lossy/f63138f38e4f4469beaaacdb00fd9b89_9366/nmd_r1-shoes.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nuK6S
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__buU5A
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fmtM9
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__ylj8N)}
                      role={"img"}
                      src={
                        "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380566/01/sv03/fnd/PNA/fmt/png/Suede-Teams-Little-Kids'-Shoes" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gy4Oo
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__piEoU
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___97PbI
                  )}
                  image={
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img___09Vbd)}
                      role={"img"}
                      src={
                        "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/226467aefe794e47a1ddac7201151dfa_9366/Superstar_360_Primeblue_Sandals_Yellow_FX4934_01_standard.jpg" as const
                      }
                    />
                  }
                  link={"/item" as const}
                  small={"small" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__otloy
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ydTmy
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__ensjx)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container434)}
            >
              <Value
                center={"center" as const}
                children2={
                  <Button
                    children2={
                      <Icon5Icon
                        className={classNames(defaultcss.all, sty.svg__xiuum)}
                        role={"img"}
                      />
                    }
                    className={classNames("__wab_instance", sty.button__enyoK)}
                    colors={"black" as const}
                    icons={"end" as const}
                    rounded={"rounded" as const}
                    slot={"Read our letter"}
                  />
                }
                className={classNames("__wab_instance", sty.value__tAmRb)}
                slot={
                  <Icon23Icon
                    className={classNames(defaultcss.all, sty.svg__oHysW)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom" as const}
                withButton={"withButton" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__isFo
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__zqSb
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__qMXb)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container433)}
            >
              <Value
                className={classNames("__wab_instance", sty.value___0T4G0)}
                slot={
                  <Icon16Icon
                    className={classNames(defaultcss.all, sty.svg___9VOJj)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__ruYGt
                  )}
                >
                  {"We guarantee everything we sell."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__jc5Bf
                  )}
                >
                  {
                    "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__a13Md)}
                  icons={"none" as const}
                  link={"link" as const}
                  slot={"View guarantee"}
                />
              </Value>

              <Value
                className={classNames("__wab_instance", sty.value__dJjh)}
                slot={
                  <Icon19Icon
                    className={classNames(defaultcss.all, sty.svg__bcM3)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__uIzuN
                  )}
                >
                  {"Know how your shoes are made."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__qxsfC
                  )}
                >
                  {
                    "Parturient blandit viverra blandit sem suspendisse himenaeos."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__ogRm)}
                  icons={"none" as const}
                  link={"link" as const}
                />
              </Value>

              <Value
                className={classNames("__wab_instance", sty.value__vBweV)}
                slot={
                  <Icon18Icon
                    className={classNames(defaultcss.all, sty.svg__hu3Fe)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__m7Y4R
                  )}
                >
                  {"Keep your shoes in play."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__xOzfl
                  )}
                >
                  {
                    "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button___7STj)}
                  icons={"none" as const}
                  link={"link" as const}
                />
              </Value>

              <Value
                className={classNames("__wab_instance", sty.value__tDc6)}
                slot={
                  <Icon17Icon
                    className={classNames(defaultcss.all, sty.svg__ihEm2)}
                    role={"img"}
                  />
                }
                topBottom={"topBottom" as const}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__uiODh
                  )}
                >
                  {"We give back for every sale."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__fexms
                  )}
                >
                  {
                    "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__k04A)}
                  icons={"none" as const}
                  link={"link" as const}
                />
              </Value>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__ctmFt)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__dwDPu
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__bUbpz
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…" as const}
                    size={1 as const}
                    type={"text" as const}
                    value={"" as const}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__bwcrS)}
                    colors={"black" as const}
                    icons={"none" as const}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___24Y5L)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__a4FTl
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box___8XXe)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__elEjb)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___9NCji
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__eL1
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__cMdQ)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vMgxg
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__d9Rn
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__ixo7S)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__toult)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gPhIl
                    )}
                  >
                    {"More info"}
                  </div>

                  <div className={classNames(defaultcss.all, sty.box__ey5N)}>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__igKya)}
                    >
                      <Button icons={"none" as const} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__dy4Mc
                        )}
                        icons={"none" as const}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__uluE4
                        )}
                        icons={"none" as const}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___8EjfE
                        )}
                        icons={"none" as const}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__ea0WO)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___5Tnri
                        )}
                        icons={"none" as const}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__fqAZt
                        )}
                        icons={"none" as const}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___3JnzA
                        )}
                        icons={"none" as const}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "container43",
    "emojiValueProps",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer",
    "textbox"
  ],
  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  container43: ["container43"],
  emojiValueProps: ["emojiValueProps"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container3: "div";
  h1: "h1";
  container4: "div";
  container: "div";
  container43: "div";
  emojiValueProps: typeof EmojiValueProps;
  container42: "div";
  container5: "div";
  container6: "div";
  container434: "div";
  container433: "div";
  footer: typeof Footer;
  textbox: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    container43: makeNodeComponent("container43"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
